# Generated by Django 3.1 on 2020-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_Id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=50)),
                ('task_description', models.TextField()),
                ('status', models.CharField(default='active', max_length=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
